name: Deploy
run-name: Deploying to npmjs

on:
  push:
    tags:
      - "*"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.com"

      - run: corepack enable

      - run: yarn install --immutable

      - run: yarn build

      - run: git config user.email "deploy@github" && git config user.name "GitHub Action"

      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
